CREATE TABLE IF NOT EXISTS "bitrefill_orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" varchar(50) NOT NULL,
	"bitrefill_invoice_id" varchar(100) NOT NULL,
	"product_id" varchar(100) NOT NULL,
	"product_name" varchar(200) NOT NULL,
	"category" varchar(50) NOT NULL,
	"amount_fiat" numeric(20, 2),
	"currency_fiat" varchar(10),
	"amount_crypto" numeric(30, 9),
	"crypto_currency" varchar(20),
	"status" varchar(20) NOT NULL DEFAULT 'pending',
	"codes" jsonb,
	"recipient_phone" varchar(20),
	"recipient_email" varchar(255),
	"payment_address" varchar(100),
	"payment_uri" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone
);
